name: guiho
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  webview_flutter: ^0.3.4
  sqflite: ^1.1.3
  android_intent: ^0.3.7+2
  device_apps: ^1.0.9
  google_fonts: ^1.1.0

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  toggle_switch: "^0.1.4"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_img.png"

flutter:

  uses-material-design: true

  assets:
    # Background, icones, botoes etc
    - assets/images/background.png
    - assets/images/HDicons/logo.png
    - assets/images/HDicons/game_2.png
    - assets/images/HDicons/book_2.png
    - assets/images/license.jpeg
    

    # Paginas manual em Portgues
    - assets/images/mport/ptpag_01.png
    - assets/images/mport/ptpag_02.png
    - assets/images/mport/ptpag_03.png
    - assets/images/mport/ptpag_04.png
    - assets/images/mport/ptpag_05.png
    - assets/images/mport/ptpag_06.png
    - assets/images/mport/ptpag_07.png
    - assets/images/mport/ptpag_08.png
    - assets/images/mport/ptpag_09.png
    - assets/images/mport/ptpag_10.png
    - assets/images/mport/ptpag_11.png
    - assets/images/mport/ptpag_12.png
    - assets/images/mport/ptpag_13.png
    - assets/images/mport/ptpag_14.png
    - assets/images/mport/ptpag_15.png
    - assets/images/mport/ptpag_16.png
    - assets/images/mport/ptpag_17.png
    - assets/images/mport/ptpag_18.png
    - assets/images/mport/ptpag_19.png

    # Paginas manual em Khrao
    - assets/images/mkrao/khpag_01.png
    - assets/images/mkrao/khpag_02.png
    - assets/images/mkrao/khpag_03.png
    - assets/images/mkrao/khpag_04.png
    - assets/images/mkrao/khpag_05.png
    - assets/images/mkrao/khpag_06.png
    - assets/images/mkrao/khpag_07.png
    - assets/images/mkrao/khpag_08.png
    - assets/images/mkrao/khpag_09.png
    - assets/images/mkrao/khpag_10.png
    - assets/images/mkrao/khpag_11.png
    - assets/images/mkrao/khpag_12.png
    - assets/images/mkrao/khpag_13.png
    - assets/images/mkrao/khpag_14.png
    - assets/images/mkrao/khpag_15.png
    - assets/images/mkrao/khpag_16.png
    - assets/images/mkrao/khpag_17.png
    - assets/images/mkrao/khpag_18.png
    - assets/images/mkrao/khpag_19.png
    - assets/images/mkrao/khpag_20.png
  #   - assets/fonts/Asap/Asap-SemiBold.ttf

  #   - google_fonts/
   
  #   - family: Asap
  #     fonts:
  #       - asset: google_fonts/
  #       - asset: assets/fonts/Asap-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  # #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
